"""initial schema

Revision ID: 6258883002d9
Revises: 
Create Date: 2026-03-26 13:02:11.611758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6258883002d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'submitted_to_printful', 'shipped', 'delivered', name='orderstatus'), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('printful_order_id', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('sizes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('dst_s3_key', sa.String(), nullable=True),
    sa.Column('stitch_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placement_zones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('add_on_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_width_mm', sa.Integer(), nullable=False),
    sa.Column('max_height_mm', sa.Integer(), nullable=False),
    sa.Column('position_on_mockup', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['placement_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('placement_zones')
    op.drop_table('uploads')
    op.drop_table('products')
    op.drop_table('orders')
    # ### end Alembic commands ###
