// Maps a (product, color, zone) tuple to its mockup PNG path.
// Convention: /public/mockups/{slug}/{color_lower}/{front|back}.png
// Generated by backend/generate_mockups.py.

import type { PlacementZone, Product } from "./types";

const BACK_ZONES = new Set(["back", "full_back"]);

export function mockupSrc(
  product: Product,
  color: string,
  zone: PlacementZone | undefined,
): string {
  const view = zone && BACK_ZONES.has(zone.name) ? "back" : "front";
  return `/mockups/${product.slug}/${color.toLowerCase()}/${view}.png`;
}

/** Card thumbnail — first variant color, front view. */
export function primaryMockupSrc(product: Product): string {
  const firstColor = product.variants[0]?.color ?? "white";
  return `/mockups/${product.slug}/${firstColor.toLowerCase()}/front.png`;
}
